### ISSUE TITLE
User can start the stop watch.

### ISSUE THREAD

**Issue by riley-rangel** [riley-rangel/stop-watch#1]
# Motivation 👍 
Giving the user the ability to start the stop watch is a **_fundamental_** feature that needs to added to give our app a good foundation! 

# Implementation 🛠 
- [x] create index.html, styles.css, and main.js in stop-watch directory
- [x] create a paragraph in index.html for 'seconds', text content should be "--"
- [x] give said paragraph an 'id' so that it can be selected with precision
- [x] add a button so the user can begin the watch, and add an 'id'
- [x] give some (minor) style, for motivation
- [x] on main.js, select the paragraph and assign to variable
- [x] select the button element and assign to variable
- [x] add a counter function
- [x] connect function to button 'click'
- [x] add additional styling
- [x] open pull request to "master" branch
- [x] merge to master and close issue

**Comment by thebearingedge** [comment]
Did you ever push this feature?

**Comment by riley-rangel** [comment]
Not yet. I closed the issue right before we left yesterday, and haven't had
a chance to push from local. Planning on it tomorrow.

**Comment by thebearingedge** [comment]
👍 Ok, as long as the feature isn't shipped, you should leave issues open until they are "addressed".

**Comment by riley-rangel** [comment]
Ok, definitely will do so in the future. Thanks Tim!
